# Generated by Django 4.1.5 on 2024-11-10 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apartments", "0005_remove_project_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("recibida", "Recibida"),
                            ("pagada", "Pagada"),
                        ],
                        default="pendiente",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=50)),
                ("persona", models.CharField(max_length=50)),
                ("fiscal_id", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("telephone", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("CP", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("terreno", "Terreno"),
                            ("soft_cost", "Soft Cost"),
                            ("hard_cost", "Hard Cost"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "subcategoria",
                    models.CharField(
                        choices=[
                            ("pre_planeacion", "Pre-planeación"),
                            (
                                "honorarios_arquitectura",
                                "Honorarios de Arquitectura e Ingeniería",
                            ),
                            ("honorarios_legales", "Honorarios Legales"),
                            ("permisos_licencias", "Permisos y Licencias"),
                            ("proyecto_ejecutivo", "Proyecto ejecutivo"),
                            ("gerencia_obra", "Gerencia de obra"),
                            ("gestion_proyecto", "Gestión del Proyecto"),
                            ("gastos_financieros", "Gastos Financieros"),
                            ("gastos_publicidad", "Gastos de Publicidad y Marketing"),
                            ("gastos_comercializacion", "Gastos de comercialización"),
                            ("otros_soft_cost", "Otros (Soft Cost)"),
                            (
                                "demolicion_preparacion",
                                "Demolición y Preparación del Terreno",
                            ),
                            ("cimentacion_estructura", "Cimentación y Estructura"),
                            (
                                "costos_materiales",
                                "Costos de Materiales de Construcción",
                            ),
                            ("electricidad_fontaneria", "Electricidad y Fontanería"),
                            ("suelos_acabados", "Suelos y Acabados"),
                            ("mobiliario_decoracion", "Mobiliario y Decoración Fijos"),
                            ("paisajismo_areas_verdes", "Paisajismo y Áreas Verdes"),
                            ("mano_obra", "Mano de Obra"),
                            ("otros_hard_cost", "Otros (Hard Cost)"),
                            ("terreno", "Terreno"),
                        ],
                        max_length=30,
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="egresos.purchaseorder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="egresos.vendor"
            ),
        ),
        migrations.CreateModel(
            name="Egreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("terreno", "Terreno"),
                            ("soft_cost", "Soft Cost"),
                            ("hard_cost", "Hard Cost"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "subcategoria",
                    models.CharField(
                        choices=[
                            ("pre_planeacion", "Pre-planeación"),
                            (
                                "honorarios_arquitectura",
                                "Honorarios de Arquitectura e Ingeniería",
                            ),
                            ("honorarios_legales", "Honorarios Legales"),
                            ("permisos_licencias", "Permisos y Licencias"),
                            ("proyecto_ejecutivo", "Proyecto ejecutivo"),
                            ("gerencia_obra", "Gerencia de obra"),
                            ("gestion_proyecto", "Gestión del Proyecto"),
                            ("gastos_financieros", "Gastos Financieros"),
                            ("gastos_publicidad", "Gastos de Publicidad y Marketing"),
                            ("gastos_comercializacion", "Gastos de comercialización"),
                            ("otros_soft_cost", "Otros (Soft Cost)"),
                            (
                                "demolicion_preparacion",
                                "Demolición y Preparación del Terreno",
                            ),
                            ("cimentacion_estructura", "Cimentación y Estructura"),
                            (
                                "costos_materiales",
                                "Costos de Materiales de Construcción",
                            ),
                            ("electricidad_fontaneria", "Electricidad y Fontanería"),
                            ("suelos_acabados", "Suelos y Acabados"),
                            ("mobiliario_decoracion", "Mobiliario y Decoración Fijos"),
                            ("paisajismo_areas_verdes", "Paisajismo y Áreas Verdes"),
                            ("mano_obra", "Mano de Obra"),
                            ("otros_hard_cost", "Otros (Hard Cost)"),
                            ("terreno", "Terreno"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("description", models.TextField()),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="egresos.vendor"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="egresos",
                        to="apartments.project",
                    ),
                ),
            ],
        ),
    ]
