# Generated by Django 4.1.5 on 2024-11-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0005_remove_project_end_date"),
        ("egresos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="project",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchaseorder",
                to="apartments.project",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("enviada", "Enviada"),
                    ("recibida", "Recibida"),
                    ("pagada", "Pagada"),
                ],
                default="pendiente",
                max_length=50,
            ),
        ),
    ]
