# Generated by Django 4.1.5 on 2024-11-12 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("egresos", "0002_purchaseorder_project_alter_purchaseorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="egreso",
            name="purchase_order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="egresos.purchaseorderitem",
            ),
        ),
    ]
