# Generated by Django 4.1.5 on 2024-11-12 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("egresos", "0003_egreso_purchase_order_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="egreso",
            name="purchase_order_item",
        ),
        migrations.AddField(
            model_name="egreso",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="egresos.purchaseorder",
            ),
        ),
    ]
