# Generated by Django 5.1.3 on 2024-11-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='color',
            field=models.CharField(default='#0000FF', max_length=7),
        ),
    ]
