# Generated by Django 5.1.3 on 2024-11-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_remove_house_height_remove_house_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='color',
            field=models.CharField(max_length=30),
        ),
    ]
