# Generated by Django 5.1.3 on 2024-12-03 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_alter_house_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='payment_schedule',
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fully_paid', models.BooleanField(default=False)),
                ('payment_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='pagos.paymentrecord')),
            ],
        ),
    ]
