# Generated by Django 4.1.5 on 2024-12-05 17:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0012_apartment_points"),
        ("clientes", "0014_meeting_oportunidad"),
        ("pagos", "0006_remove_paymentrecord_payment_schedule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id_venta",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("fecha_apartado", models.DateField(blank=True, null=True)),
                ("fecha_venta", models.DateField(blank=True, null=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventas",
                        to="apartments.apartment",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventas",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventas",
                        to="apartments.project",
                    ),
                ),
            ],
        ),
    ]
