# Generated by Django 4.1.5 on 2024-12-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0015_alter_oportunidad_estatus"),
        ("pagos", "0007_venta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentrecord",
            name="cliente",
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="oportunidad",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_records",
                to="clientes.oportunidad",
            ),
            preserve_default=False,
        ),
    ]
