# Generated by Django 4.1.5 on 2024-10-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="tipologia",
            field=models.CharField(default="A1", max_length=10),
        ),
    ]
