# Generated by Django 4.1.5 on 2024-11-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0002_apartment_tipologia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="end_date",
        ),
    ]
