# Generated by Django 4.1.5 on 2024-11-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0003_remove_project_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
