# Generated by Django 4.1.5 on 2024-11-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0005_remove_project_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
    ]
