# Generated by Django 5.1.3 on 2024-11-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_apartment_image_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
