# Generated by Django 5.1.3 on 2024-12-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tipo',
            field=models.CharField(choices=[('Vivienda Vertical', 'Vivienda vertical'), ('Lotes', 'Lotes'), ('Casas', 'Casas')], default='disponible', max_length=20),
        ),
    ]
