# Generated by Django 4.1.5 on 2024-12-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0012_apartment_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="plano",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/apartments/plano/"
            ),
        ),
    ]
