# Generated by Django 4.1.5 on 2024-11-14 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0005_remove_project_end_date"),
        ("bancos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="account_holder",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to="apartments.project",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")],
                        max_length=10,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="bancos.bankaccount",
                    ),
                ),
            ],
        ),
    ]
