# Generated by Django 4.1.5 on 2024-11-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bancos", "0002_remove_bankaccount_account_holder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
