# Generated by Django 4.1.5 on 2024-10-29 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adminacad", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccountMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("A", "Cargos Colegiatura"),
                            ("B", "Cargos Seguro"),
                            ("C", "Cargos Cuotas"),
                            ("D", "Pagos Colegiatura"),
                            ("E", "Pagos Seguro"),
                            ("F", "Pagos Cuotas"),
                        ],
                        max_length=1,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminacad.student",
                    ),
                ),
            ],
        ),
    ]
