# Generated by Django 4.1.5 on 2023-03-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Salones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salon", models.CharField(max_length=50)),
                ("grado", models.DecimalField(decimal_places=2, max_digits=5)),
                ("profesor", models.CharField(max_length=100)),
            ],
        ),
    ]
