# Generated by Django 4.1.5 on 2023-03-10 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminacad", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salones",
            name="grado",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminacad.salones",
                    ),
                ),
            ],
        ),
    ]
