# Generated by Django 4.1.5 on 2023-03-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminacad", "0002_alter_salones_grado_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="apellido",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="identificacion",
            field=models.IntegerField(default=1001),
        ),
    ]
