# Generated by Django 4.1.5 on 2023-03-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminacad", "0003_student_apellido_student_identificacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="identificacion",
            field=models.IntegerField(unique=True),
        ),
    ]
