# Generated by Django 4.1.5 on 2023-03-11 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminacad", "0004_alter_student_identificacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="identificacion",
            field=models.IntegerField(
                unique=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        2000,
                        message="Identificacion must be less than or equal to 2000.",
                    ),
                    django.core.validators.MinValueValidator(
                        1000,
                        message="Identificacion must be greater than or equal to 1000.",
                    ),
                ],
            ),
        ),
    ]
