# Generated by Django 4.1.7 on 2023-03-11 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminacad", "0006_materias"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="grado",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="adminacad.salones",
            ),
            preserve_default=False,
        ),
    ]
