# Generated by Django 4.1.7 on 2023-03-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminacad", "0007_student_grado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calif", models.IntegerField()),
                (
                    "identificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminacad.student",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminacad.materias",
                    ),
                ),
            ],
        ),
    ]
