# Generated by Django 4.1.7 on 2023-03-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminacad", "0008_calificacion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="materias",
            old_name="nombre",
            new_name="nombre_materia",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="apellido",
            new_name="apellido_est",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="nombre",
            new_name="nombre_est",
        ),
    ]
