# Generated by Django 4.1.7 on 2023-03-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminacad", "0009_rename_nombre_materias_nombre_materia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calificacion",
            name="calif",
            field=models.IntegerField(default=0),
        ),
    ]
