# Generated by Django 4.1.7 on 2023-03-11 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminacad", "0010_alter_calificacion_calif"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="calificacion",
            unique_together={("identificacion", "materia")},
        ),
    ]
