# Generated by Django 4.1.7 on 2023-03-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminacad", "0011_alter_calificacion_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="calificacion",
            name="calif_1B",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calificacion",
            name="calif_2B",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calificacion",
            name="calif_3B",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calificacion",
            name="calif_4B",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calificacion",
            name="calif_5B",
            field=models.IntegerField(default=0),
        ),
    ]
