# Generated by Django 4.1.5 on 2024-10-29 19:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apartments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imprevistos_hard", models.FloatField(default=5.0)),
                ("iva_hard_cost", models.FloatField(default=16.0)),
                ("pre_planeacion", models.FloatField(default=2.0)),
                ("tramites_permisos", models.FloatField(default=3.0)),
                ("legal_fiscal", models.FloatField(default=2.5)),
                ("proyecto_ejecutivo", models.FloatField(default=6.0)),
                ("gerencia_de_obra", models.FloatField(default=7.0)),
                ("ingenierias_estudios", models.FloatField(default=1.5)),
                ("fee_desarrollo", models.FloatField(default=8.0)),
                ("comercializacion", models.FloatField(default=3.0)),
                ("mercadotecnia", models.FloatField(default=2.5)),
                ("imprevistos_soft", models.FloatField(default=5.0)),
                ("iva_soft_cost", models.FloatField(default=16.0)),
                ("inflacion", models.FloatField(default=4.0)),
                ("tasa_interes", models.FloatField(default=7.0)),
                ("caja_inicial", models.FloatField(default=10000.0)),
                ("comision_contraventa", models.FloatField(default=1.0)),
                ("comision_contraescritura", models.FloatField(default=1.0)),
                (
                    "fecha_inicio_proyecto",
                    models.DateField(default=datetime.datetime.today),
                ),
                ("mes_inicio_proyecto", models.IntegerField(default=1)),
                (
                    "fecha_fin_proyecto",
                    models.DateField(default=datetime.datetime.today),
                ),
                (
                    "fecha_inicio_preventa",
                    models.DateField(default=datetime.datetime.today),
                ),
                (
                    "fecha_inicio_construccion",
                    models.DateField(default=datetime.datetime.today),
                ),
                (
                    "fecha_fin_construccion",
                    models.DateField(default=datetime.datetime.today),
                ),
                (
                    "fecha_inicio_preplaneacion",
                    models.DateField(default=datetime.datetime.today),
                ),
                (
                    "fecha_fin_preplaneacion",
                    models.DateField(default=datetime.datetime.today),
                ),
                ("fecha_inicio_mkt", models.DateField(default=datetime.datetime.today)),
                ("fecha_fin_mkt", models.DateField(default=datetime.datetime.today)),
                (
                    "fecha_inicio_tramites",
                    models.DateField(default=datetime.datetime.today),
                ),
                (
                    "fecha_fin_tramites",
                    models.DateField(default=datetime.datetime.today),
                ),
                (
                    "fecha_inicio_legal_fiscal",
                    models.DateField(default=datetime.datetime.today),
                ),
                (
                    "fecha_fin_legal_fiscal",
                    models.DateField(default=datetime.datetime.today),
                ),
                (
                    "fecha_inicio_proy_ejecutivo",
                    models.DateField(default=datetime.datetime.today),
                ),
                (
                    "fecha_fin_proy_ejecutivo",
                    models.DateField(default=datetime.datetime.today),
                ),
                ("superficie_terreno", models.FloatField(blank=True, null=True)),
                ("costo_terreno", models.FloatField(blank=True, null=True)),
                ("cesion_municipal", models.FloatField(blank=True, null=True)),
                ("vialidades_pavimentos", models.FloatField(blank=True, null=True)),
                (
                    "jardines_amenidades_externas",
                    models.FloatField(blank=True, null=True),
                ),
                ("areas_amenidades_lotes", models.FloatField(blank=True, null=True)),
                ("areas_comunes_lotes", models.FloatField(blank=True, null=True)),
                ("numero_lotes", models.IntegerField(blank=True, null=True)),
                ("tamaño_promedio_lotes", models.FloatField(blank=True, null=True)),
                ("valor_inicial_lotes", models.FloatField(blank=True, null=True)),
                ("absorcion_mensual_lotes", models.IntegerField(blank=True, null=True)),
                (
                    "escrituracion_por_mes_lotes",
                    models.IntegerField(blank=True, null=True),
                ),
                ("precio_venta_lotes", models.FloatField(blank=True, null=True)),
                ("enganche_lotes", models.FloatField(blank=True, null=True)),
                ("financiamiento_lotes", models.FloatField(blank=True, null=True)),
                ("liquidacion_lotes", models.FloatField(blank=True, null=True)),
                (
                    "plazo_financiamiento_lotes",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "incremento_precio_por_ud_vendidas_lotes",
                    models.FloatField(blank=True, null=True),
                ),
                ("incremento_precio_lotes", models.FloatField(blank=True, null=True)),
                ("costo_area_vendible_lotes", models.FloatField(blank=True, null=True)),
                ("costo_amenidades_externas", models.FloatField(blank=True, null=True)),
                (
                    "costo_vialidades_pavimentos",
                    models.FloatField(blank=True, null=True),
                ),
                ("costo_exterior_municipal", models.FloatField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="apartments.project",
                    ),
                ),
            ],
        ),
    ]
