# Generated by Django 4.1.5 on 2024-11-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectcost",
            old_name="precio_venta_lotes",
            new_name="precio_por_m2",
        ),
    ]
