# Generated by Django 4.1.5 on 2024-11-16 14:15

import analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_remove_projectcost_valor_inicial_lotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcost",
            name="fecha_fin_proyecto",
            field=models.DateField(
                default=analysis.models.ProjectCost.default_fecha_fin_proyecto
            ),
        ),
        migrations.AlterField(
            model_name="projectcost",
            name="fecha_inicio_preventa",
            field=models.DateField(
                default=analysis.models.ProjectCost.default_fecha_inicio_preventa
            ),
        ),
    ]
