# Generated by Django 4.1.5 on 2024-11-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cliente",
            old_name="id",
            new_name="id_client",
        ),
    ]
