# Generated by Django 4.1.5 on 2024-11-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_cliente_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="estatus",
            field=models.CharField(
                choices=[
                    ("lead", "Lead"),
                    ("cliente", "Cliente"),
                    ("inactivo", "Inactivo"),
                ],
                max_length=50,
            ),
        ),
    ]
