# Generated by Django 4.1.5 on 2024-11-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0007_alter_cliente_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
