# Generated by Django 5.1.3 on 2024-11-26 14:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_remove_apartment_price_per_m2_alter_project_image'),
        ('clientes', '0010_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='interaction_status',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='last_interaction',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='modo_contacto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='project',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_propiedad',
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id_oportunidad', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('estatus', models.CharField(choices=[('prospecto', 'Prospecto'), ('en_progreso', 'En Progreso'), ('cerrado', 'Cerrado')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('interaction_status', models.CharField(choices=[('Recent', 'Recent'), ('Stale', 'Stale'), ('No Interaction', 'No Interaction')], default='No Interaction', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='clientes.cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_oportunidades', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='apartments.project')),
            ],
        ),
    ]
