# Generated by Django 5.1.3 on 2024-11-26 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_remove_oportunidad_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='oportunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='clientes.oportunidad'),
        ),
    ]
