# Generated by Django 5.1.3 on 2024-11-26 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_interaction_oportunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='oportunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='clientes.oportunidad'),
        ),
    ]
