# Generated by Django 4.1.5 on 2024-12-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0014_meeting_oportunidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oportunidad",
            name="estatus",
            field=models.CharField(
                choices=[
                    ("prospecto", "Prospecto"),
                    ("en_progreso", "En Progreso"),
                    ("cerrado", "Cerrado"),
                    ("vendido", "Vendido"),
                ],
                max_length=50,
            ),
        ),
    ]
